import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";

const SRC = "assets/Gemini_Generated_Image_lat777lat777lat7.jpg";
const BG = [254, 254, 254];
// Below this distance-from-background, fully transparent. Above this,
// fully opaque. Between: linear alpha ramp for clean anti-aliased edges.
const T_LOW = 12;
const T_HIGH = 40;

function dist(r, g, b) {
  const dr = r - BG[0], dg = g - BG[1], db = b - BG[2];
  return Math.sqrt(dr * dr + dg * dg + db * db);
}

async function main() {
  const { data, info } = await sharp(SRC).raw().ensureAlpha().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;

  for (let i = 0; i < data.length; i += channels) {
    const d = dist(data[i], data[i + 1], data[i + 2]);
    let alpha;
    if (d <= T_LOW) alpha = 0;
    else if (d >= T_HIGH) alpha = 255;
    else alpha = Math.round(((d - T_LOW) / (T_HIGH - T_LOW)) * 255);
    data[i + 3] = alpha;
  }

  const cutout = sharp(data, { raw: { width, height, channels } }).png();

  mkdirSync("src/assets/logo", { recursive: true });
  mkdirSync("icons", { recursive: true });

  // Trim transparent margins, keep a small even padding.
  const trimmed = await cutout.clone().trim({ threshold: 1 }).toBuffer();
  const trimmedMeta = await sharp(trimmed).metadata();
  const pad = Math.round(Math.max(trimmedMeta.width, trimmedMeta.height) * 0.06);

  const master = await sharp(trimmed)
    .extend({ top: pad, bottom: pad, left: pad, right: pad, background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();

  await sharp(master).resize(512, 512, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } }).toFile("src/assets/logo/logo-512.png");
  await sharp(master).resize(96, 96, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } }).toFile("src/assets/logo/logo-96.png");

  for (const size of [16, 32, 48, 128]) {
    await sharp(master)
      .resize(size, size, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .toFile(`icons/${size}.png`);
  }

  // Small inline copy for content-script UI (toolbar trigger, popup header) —
  // embedded as a data URI so it needs no web_accessible_resources entry and
  // no runtime.getURL round trip inside the page context.
  const inlineBuf = await sharp(master)
    .resize(64, 64, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  const dataUri = `data:image/png;base64,${inlineBuf.toString("base64")}`;
  writeFileSync(
    "src/assets/logo-data-uri.js",
    `// Generated by scripts/process-logo.js — do not edit by hand.\nexport const LOGO_DATA_URI = "${dataUri}";\n`
  );

  const meta = await sharp(master).metadata();
  console.log("master size:", meta.width, meta.height);
  console.log("inline data URI bytes:", dataUri.length);
  console.log("done");
}

main();
